miniblog/miniblog/urls.py
from django.contrib import admin
from django.urls import path
from blogapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home),
    path('about/',views.about,name='about'), #this name=about is needed for link about page in nav bar
    path('contact/',views.contact,name='contact'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('login/',views.user_login,name='login'),
    path('signup/',views.user_signup,name='signup'),
    path('logout/',views.user_logout,name='logout'),
    path('addpost/',views.add_Post,name='addpost'),

    #for update post need dynamic url q ki jis post ke liye update krna wo specific post cahiye hoga
    path('updatepost/<int:id>',views.update_Post,name='updatepost'),
    path('deletepost/<int:id>',views.delet_Post,name='deletepost'),
    
]

miniblog/blogapp/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=150)
    desc=models.TextField()

miniblog/blogapp/forms.py
from django import forms
#usrcreationform and authoten(login) these form is given by djangoand we only customized it
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext,gettext_lazy as _
from .models import Post

class  SignUpForm(UserCreationForm):
    password1 = forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Confirm Password(again)',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model =User
        fields = ['username','first_name','last_name','email']
        labels = {'first_name':'First Name','last_name':'Last Name','email':'Email'}
        widgets = {'username':forms.TextInput(attrs={'class':'form-control'}),'first_name':forms.TextInput(attrs={'class':'form-control'}),'last_name':forms.TextInput(attrs={'class':'form-control'}),'email':forms.EmailInput(attrs={'class':'form-control'})}


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus':True,'class':'form-control'}))
    password = forms.CharField(label=_('password'),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'}))

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields = ['title','desc']
        labels = {'title':'Title' ,'desc':'Description'}
        widgets ={'title': forms.TextInput(attrs={'class':'form-control'}),'desc':forms.Textarea(attrs={'class':'form-control'})}

miniblog/blogapp/views.py
from django.shortcuts import render,HttpResponseRedirect
from .forms import SignUpForm,LoginForm,PostForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from .models import Post
from django.contrib.auth.models import Group

def home(request):
    posts=Post.objects.all() 
    return render(request, 'blogapp/home.html',{'posts':posts})#

def about(request):
    return render(request ,'blogapp/about.html')

def contact(request):
    return render(request ,'blogapp/contact.html')

#dasbord will be accese by only authenticated people
#so those user not have logined and try to acces dashboard send them in login page
def dashboard(request):
    if request.user.is_authenticated:
        posts = Post.objects.all()
        #for getting full name from database we have a built in method full_name
        user = request.user
        full_name = user.get_full_name()
        gps=user.groups.all()
        return render(request ,'blogapp/dashboard.html',{'posts':posts,'full_name':full_name,'groups':gps})
    else:
        return HttpResponseRedirect('/login.html/')

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')

def user_signup(request):
    if request.method=="POST":
        form=SignUpForm(request.POST)
        if form.is_valid():
            messages.success(request,"Congraluations ! You have become an Author, Thanks for be member!")
            user = form.save()
            group = Group.objects.get(name='Author')
            user.groups.add(group)
    else:
        form = SignUpForm()
    return render(request ,'blogapp/signup.html',{'form':form})

def user_login(request):
    if not request.user.is_authenticated:
        if request.method=="POST":
            form = LoginForm(request=request ,data=request.POST)
            if form.is_valid():
                uname=form.cleaned_data['username']
                upassword=form.cleaned_data['password']
                user=authenticate(username=uname,password=upassword)
                if user is not None:
                    login(request,user)
                    messages.success(request,"Loged in success")
                    return HttpResponseRedirect('/dashboard/')
        else:
            form=LoginForm()
        return render(request,'blogapp/login.html',{'form':form}) 
        return HttpResponseRedirect('/dashboard/')

def add_Post(request):
    if request.user.is_authenticated:
        if request.method=="POST":
            form = PostForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data['title']
                desc = form.cleaned_data['desc']
                #title->database wala title,title->form se ane wala title
                pst = Post(title=title,desc=desc)
                pst.save()
                form = PostForm() 
        else:
            form = PostForm()
        return render(request,'blogapp/addpost.html',{'form':form})
    else:
        return HttpResponseRedirect('/login')

def update_Post(request,id):
    if request.user.is_authenticated:
        if request.method=="POST":
            pi = Post.objects.get(pk=id)
            form = PostForm(request.POST,instance=pi)
            if form.is_valid():
                form.save()
        else:
            pi = Post.objects.get(pk=id)
            form = PostForm(instance=pi)
        return render(request,'blogapp/update.html',{'form':form})
    else:
        return HttpResponseRedirect('/login')

def delet_Post(request,id):
    if request.user.is_authenticated:
        if request.method=="POST":
            pi = Post.objects.get(pk=id)
            pi.delete()
            return HttpResponseRedirect('/dashboard/')
    else:
        return HttpResponseRedirect('/login')

miniblog/blogapp/templates/blogapp/about.html
{% extends 'blogapp/base.html' %}
{% load static %}


{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">About Page</h3>
    <p>this is aparagraph using for test purposee</p>
</div>
{% endblock content %}

miniblog/blogapp/templates/blogapp/addpost.html
{% extends 'blogapp/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Dashboard/ Add Post</h3>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Add" class="btn btn-success">
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
    </form>
</div>
{% endblock content %}

miniblog/blogapp/templates/blogapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'blogapp/css/bootstrap.css'%}">
        <link rel="stylesheet" href="{% static 'blogapp/css/style.css'%}">
    </head>
    <body>
        <div class="container-fluid bg-dark">
            {% include 'blogapp/navbar.html' %}
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    {% block msg %}
                    {% endblock msg %}
                </div>
            </div>

            <div class="row">
                {% block side %}
                {% endblock side %}

                {% block content %}
                {% endblock content %}
            </div>
        </div>

        
    
        
        <script src="{% static 'blogapp/js/jquery.js'%}"></script>
        <script src="{% static 'blogapp/js/popper.js'%}"></script>
        <script src="{% static 'blogapp/js/bootstrap.js'%}"></script>
    </body>
</html>

miniblog/blogapp/templates/blogapp/contact.html
{% extends 'blogapp/base.html' %}
{% load static %}


{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Contact page</h3>
    <form>
        <div class="form-group">
            <label for="exampleInputName">Name</label>
            <input type="name" class="form-control" id="exampleInputEmail" placeholder="Enter name">
          </div>

        <div class="form-group">
          <label for="exampleInputEmail">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
        </div>

        <div class="form-group">
            <label for="exampleInputEmail">Address</label>
            <input type="address" class="form-control" id="exampleInputEmail1"  placeholder="Enter your address">
        </div>

        <div class="form-group">
            <label for="exampleInputMessage">Message</label>
            <textarea class="form-control" id="message" rows="3"></textarea>
            <input type="address" class="form-control" id="exampleInputEmail1"  placeholder="Enter your address">
        </div>
    
        

        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</div>
{% endblock content %}

miniblog/blogapp/templates/blogapp/dashboard.html
{% extends 'blogapp/base.html' %}
{% load static %}

{% block msg %}
    {% if messages %}
        {% for message in messages %}
            <div{% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}>
                <strong> {{message}} </strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
{% endblock msg %}

{% block side %}
<div class="col-sm-2 text-white my-5 text-center">
    <h4 class="my-5">Profile</h4.
    <h5> {{full_name}}</h5>
    {% for group in groups %}
        <p>{{group.name}}</p>
    {% endfor %}
</div>
{% endblock side %}




{% comment %} in content we have to create a table for showing a post {% endcomment %}

{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Dashboard Page</h3>
{% comment %} creat another buttom for add post {% endcomment %}
    <a href="{% url 'addpost' %}" class="btn btn-success">Add post</a>
    <h4 class="text-center alert alert-info mt-3">Show Post Information</h4>

    {% if posts %}
        <table class="table table-hover bg-white">
            <thead>
                <tr class="text-center">
                    <th scope="col" style="width: 2%">ID</th>
                    <th scope="col" style="width: 28%">Title</th>
                    <th scope="col" style="width: 55%">Description</th>
                    <th scope="col" style="width: 15%">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                    <tr>
                        <th scope="row">{{post.id}} </th>
                        <td>{{post.title}}</td>
                        <td>{{post.desc}}</td>
                        <td class="text-center">
                            <a href="{% url 'updatepost' post.id %}" class="btn btn-warning btn-sm">Edit</a>
                            
                            {% comment %} those have permision for delete they only {% endcomment %}
                            {% if perms.blogapp.delete_post %}
                                <form action="{% url 'deletepost' post.id %}" method="post" class="d-inline">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                                </form>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h4 class="text-center alert alert-warning">No Records </h4>
    {% endif %}
</div>
{% endblock content %}

miniblog/blogapp/templates/blogapp/home.html
{% extends 'blogapp/base.html' %}
{% load static %}


{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Home Page</h3>
    {%for post in posts%}
      <div class="jumbotron jumbotron-fluid jumbo-color">
        <div class="container">
          <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
          <p class="lead">{{post.desc}}</p>
        </div>
      </div>
    {% endfor %}
</div>
{% endblock content %}

miniblog/blogapp/templates/blogapp/login.html
{% extends 'blogapp/base.html' %}
{% load static %}


{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Login Page</h3>
    <form action ="" method = "post" novalidate>
        {% csrf_token %}
        {% for i in form %}
            <div class = "form-group">
                {{i.label_tag}}{{i}} <small class="text-danger"> {{i.errors |striptags}} </small>  {{i.errors |striptags}}
            </div>
        {% endfor %}

        <input type="submit" value="Submit" class="btn btn-primary">
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors%}
            <p class='alert-danger my-3'>{{error}}</p>
            {% endfor %}
        {% endif %}
    </form>
</div>
{% endblock content %} 

miniblog/blogapp/templates/blogapp/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <a class="navbar-brand" href="#">Mini Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
          
        </li>


        {% comment %} {%url 'contact'%}
        {%url 'dashboard'%}
        {%url 'signup'%}
        {%url 'login'%}
        {%url 'logout'%} {% endcomment %}


        <li class="nav-item">
          <a class="nav-link" href="{%url 'contact'%}">Contact</a>
        </li>
      
        {%if request.user.is_authenticated %}
          <li class="nav-item">
              <a class="nav-link" href="{%url 'dashboard'%}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'logout'%}">Logout</a>
          </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{%url 'signup'%}">Signup</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{%url 'login'%}">Login</a>
        </li>
      {% endif %}
        
      </ul>
    </div>
  </nav>

miniblog/blogapp/templates/blogapp/signup.html
{% extends 'blogapp/base.html' %}
{% load static %}


{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Become an Author</h3>
    {% if messages %}
        {% for m in messages %}
            <p {% if m.tags%} class="alert alert-{{m.tags}} mb-5" {% endif %}>{{m}} </p>
        {% endfor %}
    {% endif %}
    {% comment %} this is by default form by djgo admin{{form.as_p}} {% endcomment %}
    <form action ="" method = "post" novalidate>
        {% csrf_token %}
        {% for i in form %}
            <div class = "form-group">
                {{i.label_tag}}  {{i}}  <small class="text-danger"> {{i.errors |striptags}} </small>
            </div>
        {% endfor %}

        <input type="submit" value="SignUp" class="btn btn-primary">
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors%}
                <p class='alert-danger my-3'>{{error}}</p>
            {% endfor %}
        {% endif %}
    </form>
</div>

{% endblock content %}

miniblog/blogapp/templates/blogapp/update.html
{% extends 'blogapp/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Dashboard/ Update Post</h3>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update" class="btn btn-success">
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
    </form>
</div>
{% endblock content %}